apiVersion: v1
kind: Service
metadata:
  name: stocks-service
  namespace: stocks
spec:
  selector:
    app: stocks-app
  type: ClusterIP 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
