apiVersion: v1
kind: Service
metadata:
  name: capital-gains-service
  namespace: stocks
spec:
  selector:
    app: capital-gains-app
  type: NodePort 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30081
