apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
  namespace: stocks
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 500Mi
      