apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: stocks
spec:
  selector:
    app: mongo
  type: ClusterIP # NodePort 
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      # nodePort: 30080
